# Generated by Django 2.1.8 on 2021-05-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('url', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1023)),
                ('pnrate', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('day0', models.IntegerField(default=0)),
                ('day1', models.IntegerField(default=0)),
                ('day2', models.IntegerField(default=0)),
                ('day3', models.IntegerField(default=0)),
                ('day4', models.IntegerField(default=0)),
                ('day5', models.IntegerField(default=0)),
                ('predict', models.IntegerField(default='0', null=True)),
            ],
        ),
    ]
