# Generated by Django 2.1.8 on 2021-05-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pnrate',
            field=models.FloatField(default=1),
        ),
    ]
